---
- name: Check Multiple FortiGate Interface Status
  hosts: fortigates
  gather_facts: false

  collections:
    - fortinet.fortios

 tasks:

    - name: Get FortiGate interface status
      fortinet.fortios.fortios_monitor_fact:
        vdom: root
        selector: system_interface
      register: fortigate_interfaces

    - name: Display interface status
      ansible.builtin.debug:
        msg: {{ item.name }} : {{ item.link }}
      loop: {{ fortigate_interfaces.meta.results }}
