---
- name: Check Multiple FortiGate Interface Status
  hosts: fortigates
  gather_facts: false

  collections:
    - fortinet.fortios

  vars:
    target_interfaces:
      - port11
      - port12

  tasks:

    - name: Get FortiGate interface information
      fortinet.fortios.fortios_monitor_fact:
        vdom: "root"
        selector: "system_interface_select"
      register: interface_info

    - name: Display selected interface information
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ interface_info.meta.results }}"
      when: item.name in target_interfaces
